### ISSUE TITLE
Error in connecting with Magento.

### ISSUE THREAD

**Issue by KlwntSingh** [hotwaxlabs/magento#1]
Following error message is showing when i try to connect to magento api from <strong>Magento Integration Manager</strong>
`Error in connecting with Magento. Error Message: {urn:Magento}Mage_Api_Model_Server_Wsi_HandlerPort is not a valid port. Valid ports are: {urn:Magento}Port`

Please Help !
Thanks

**Comment by KlwntSingh** [comment]
Hello,
I resolved my issue.
I was first using older version of magento i.e 1.9.2.0 than i tried 1.9.1.0 and i also didn't worked and than i tried 1.9.0 and it worked.
By the way, Great component for syncing magento with ofbiz.
Thanks,

**Comment by arunpati** [comment]
Thanks Kulwant for reporting the issue. We will soon provide support to Magento latest version as well.

**Comment by CyborTronik** [comment]
Is there a workaround for that?

**Comment by KlwntSingh** [comment]
Use magneto version 1.9.0

**Comment by kevinwu** [comment]
Is there any other solution except for downgrading versions, which is IMO not a good solution?

**Comment by KlwntSingh** [comment]
There might be by by changing code in magento which give wrong xml response.
